const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  BRANCH_MANAGER: 'BRANCH_MANAGER'
});

const TRIP_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_TRANSIT: 'IN_TRANSIT',
  COMPLETED: 'COMPLETED',
  INVOICED: 'INVOICED',
  PAID: 'PAID'
});

const TRIP_STATUS_ORDER = [
  TRIP_STATUS.PENDING,
  TRIP_STATUS.ASSIGNED,
  TRIP_STATUS.IN_TRANSIT,
  TRIP_STATUS.COMPLETED,
  TRIP_STATUS.INVOICED,
  TRIP_STATUS.PAID
];

// Allowed forward transitions via PUT /trips/:id/status.
// INVOICED and PAID have their own dedicated endpoints (approve, mark-paid).
const ALLOWED_STATUS_TRANSITIONS = {
  PENDING: ['ASSIGNED'],
  ASSIGNED: ['IN_TRANSIT'],
  IN_TRANSIT: ['COMPLETED'],
  COMPLETED: [],
  INVOICED: [],
  PAID: []
};

const PAYMENT_METHODS = Object.freeze({
  MOBILE_MONEY: 'MOBILE_MONEY',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CASH: 'CASH'
});

const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED'
});

const INVOICE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PAID: 'PAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  OVERDUE: 'OVERDUE'
});

const AUDIT_ACTIONS = Object.freeze({
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  STATUS_CHANGE: 'STATUS_CHANGE',
  APPROVE: 'APPROVE',
  INVOICE: 'INVOICE',
  MARK_PAID: 'MARK_PAID'
});

const SERVICE_FEE_RATE = 0.05;

const MAX_LOGIN_ATTEMPTS = 5;
const LOCK_TIME_MS = 30 * 60 * 1000; // 30 minutes

module.exports = {
  ROLES,
  TRIP_STATUS,
  TRIP_STATUS_ORDER,
  ALLOWED_STATUS_TRANSITIONS,
  PAYMENT_METHODS,
  USER_STATUS,
  INVOICE_STATUS,
  AUDIT_ACTIONS,
  SERVICE_FEE_RATE,
  MAX_LOGIN_ATTEMPTS,
  LOCK_TIME_MS
};
